muban.mxpro.二级.desc = '.module-info-item:eq(4)&&Text;;;.module-info-item-content:eq(1)&&Text;.module-info-item-content:eq(0)&&Text';
muban.mxpro.二级.tabs = '#y-playList .tab-item';
var rule = {
    title:'起飞',
    模板:'mxpro',
    host:'https://fun.tvoled.net',
    url:'/index.php/vod/show/id/fyfilter.html',
    filterable:1,//是否启用分类筛选,
    filter_url:'{{fl.cateId}}{{fl.area}}{{fl.by}}{{fl.class}}{{fl.lang}}/page/fypage{{fl.year}}',
    filter:{
        "1":[
{"key":"class","name":"分类","value":[
{"n":"全部","v":""},
{"n":"Netflix","v":"Netflix"},
{"n":"喜剧","v":"/class/喜剧"},
{"n":"爱情","v":"/class/爱情"},
{"n":"恐怖","v":"/class/恐怖"},
{"n":"丧尸","v":"/class/丧尸"},
{"n":"动作","v":"/class/动作"},
{"n":"科幻","v":"/class/科幻"},
{"n":"剧情","v":"/class/剧情"},
{"n":"战争","v":"/class/战争"},
{"n":"灾难","v":"/class/灾难"},
{"n":"犯罪","v":"/class/犯罪"},
{"n":"动画","v":"/class/动画"},
{"n":"奇幻","v":"/class/奇幻"},
{"n":"冒险","v":"/class/冒险"},
{"n":"悬疑","v":"/class/悬疑"},
{"n":"惊悚","v":"/class/惊悚"},
{"n":"纪录","v":"/class/纪录"},
{"n":"网络电影","v":"/class/网络电影"}
]},
{"key":"area","name":"地区","value":[
{"n":"全部","v":""},
{"n":"大陆","v":"/area/大陆"},
{"n":"香港","v":"/area/香港"},
{"n":"台湾","v":"/area/台湾"},
{"n":"美国","v":"/area/美国"},
{"n":"韩国","v":"/area/韩国"},
{"n":"日本","v":"/area/日本"},
{"n":"泰国","v":"/area/泰国"},
{"n":"新加坡","v":"/area/新加坡"},
{"n":"马来西亚","v":"/area/马来西亚"},
{"n":"印度","v":"/area/印度"}
]},
{"key":"year","name":"年份","value":[
{"n":"全部","v":""},
{"n":"2023","v":"/year/2023"},
{"n":"2022","v":"/year/2022"},
{"n":"2021","v":"/year/2021"},
{"n":"2020","v":"/year/2020"},
{"n":"2019","v":"/year/2019"},
{"n":"2018","v":"/year/2018"},
{"n":"2017","v":"/year/2017"},
{"n":"2016","v":"/year/2016"},
{"n":"2015","v":"/year/2015"},
{"n":"2014","v":"/year/2014"},
{"n":"2013","v":"/year/2013"},
{"n":"2012","v":"/year/2012"},
{"n":"2011","v":"/year/2011"},
{"n":"2010","v":"/year/2010"}
]},
{"key":"lang","name":"语言","value":[
{"n":"全部","v":""},
{"n":"国语","v":"/lang/国语"},
{"n":"英语","v":"/lang/英语"},
{"n":"粤语","v":"/lang/粤语"},
{"n":"闽南语","v":"/lang/闽南语"},
{"n":"韩语","v":"/lang/韩语"},
{"n":"日语","v":"/lang/日语"}
]},
{"key":"by","name":"排序","value":[
{"n":"时间","v":"/by/time"},
{"n":"人气","v":"/by/hits"},
{"n":"评分","v":"/by/score"}
]}],
"2":[
{"key":"class","name":"分类","value":[
{"n":"全部","v":""},
{"n":"Netflix","v":"/class/Netflix"},
{"n":"古装","v":"/class/古装"},
{"n":"战争","v":"/class/战争"},
{"n":"喜剧","v":"/class/喜剧"},
{"n":"丧尸","v":"/class/丧尸"},
{"n":"家庭","v":"/class/家庭"},
{"n":"犯罪","v":"/class/犯罪"},
{"n":"动作","v":"/class/动作"},
{"n":"奇幻","v":"/class/奇幻"},
{"n":"剧情","v":"/class/剧情"},
{"n":"科幻","v":"/class/科幻"},
{"n":"惊悚","v":"/class/惊悚"},
{"n":"恐怖","v":"/class/恐怖"},
{"n":"悬疑","v":"/class/悬疑"},
{"n":"穿越","v":"/class/穿越"}
]},
{"key":"area","name":"地区","value":[
{"n":"全部","v":""},
{"n":"大陆","v":"/area/大陆"},
{"n":"香港","v":"/area/香港"},
{"n":"台湾","v":"/area/台湾"},
{"n":"美国","v":"/area/美国"},
{"n":"韩国","v":"/area/韩国"},
{"n":"日本","v":"/area/日本"},
{"n":"泰国","v":"/area/泰国"},
{"n":"新加坡","v":"/area/新加坡"},
{"n":"马来西亚","v":"/area/马来西亚"},
{"n":"印度","v":"/area/印度"}
]},
{"key":"year","name":"年份","value":[
{"n":"全部","v":""},
{"n":"2023","v":"/year/2023"},
{"n":"2022","v":"/year/2022"},
{"n":"2021","v":"/year/2021"},
{"n":"2020","v":"/year/2020"},
{"n":"2019","v":"/year/2019"},
{"n":"2018","v":"/year/2018"},
{"n":"2017","v":"/year/2017"},
{"n":"2016","v":"/year/2016"},
{"n":"2015","v":"/year/2015"},
{"n":"2014","v":"/year/2014"},
{"n":"2013","v":"/year/2013"},
{"n":"2012","v":"/year/2012"},
{"n":"2011","v":"/year/2011"},
{"n":"2010","v":"/year/2010"}
]},
{"key":"lang","name":"语言","value":[
{"n":"全部","v":""},
{"n":"国语","v":"/lang/国语"},
{"n":"英语","v":"/lang/英语"},
{"n":"粤语","v":"/lang/粤语"},
{"n":"闽南语","v":"/lang/闽南语"},
{"n":"韩语","v":"/lang/韩语"},
{"n":"日语","v":"/lang/日语"}
]},
{"key":"by","name":"排序","value":[
{"n":"时间","v":"/by/time"},
{"n":"人气","v":"/by/hits"},
{"n":"评分","v":"/by/score"}
]}],
"3":[
{"key":"class","name":"分类","value":[
{"n":"全部","v":""},
{"n":"真人秀","v":"/class/真人秀"},
{"n":"游戏","v":"/class/游戏"},
{"n":"亲子","v":"/class/亲子"},
{"n":"音乐","v":"/class/音乐"},
{"n":"搞笑","v":"/class/搞笑"},
{"n":"少儿","v":"/class/少儿"},
{"n":"纪录","v":"/class/纪录"}
]},
{"key":"area","name":"地区","value":[
{"n":"全部","v":""},
{"n":"大陆","v":"/area/大陆"},
{"n":"香港","v":"/area/香港"},
{"n":"台湾","v":"/area/台湾"},
{"n":"美国","v":"/area/美国"},
{"n":"韩国","v":"/area/韩国"},
{"n":"日本","v":"/area/日本"},
{"n":"泰国","v":"/area/泰国"},
{"n":"新加坡","v":"/area/新加坡"},
{"n":"马来西亚","v":"/area/马来西亚"},
{"n":"印度","v":"/area/印度"}
]},
{"key":"year","name":"年份","value":[
{"n":"全部","v":""},
{"n":"2023","v":"/year/2023"},
{"n":"2022","v":"/year/2022"},
{"n":"2021","v":"/year/2021"},
{"n":"2020","v":"/year/2020"},
{"n":"2019","v":"/year/2019"},
{"n":"2018","v":"/year/2018"},
{"n":"2017","v":"/year/2017"},
{"n":"2016","v":"/year/2016"},
{"n":"2015","v":"/year/2015"},
{"n":"2014","v":"/year/2014"},
{"n":"2013","v":"/year/2013"},
{"n":"2012","v":"/year/2012"},
{"n":"2011","v":"/year/2011"},
{"n":"2010","v":"/year/2010"}
]},
{"key":"lang","name":"语言","value":[
{"n":"全部","v":""},
{"n":"国语","v":"/lang/国语"},
{"n":"英语","v":"/lang/英语"},
{"n":"粤语","v":"/lang/粤语"},
{"n":"闽南语","v":"/lang/闽南语"},
{"n":"韩语","v":"/lang/韩语"},
{"n":"日语","v":"/lang/日语"}
]},
{"key":"by","name":"排序","value":[
{"n":"时间","v":"/by/time"},
{"n":"人气","v":"/by/hits"},
{"n":"评分","v":"/by/score"}
]}],
"4":[
{"key":"area","name":"地区","value":[
{"n":"全部","v":""},
{"n":"大陆","v":"/area/大陆"},
{"n":"香港","v":"/area/香港"},
{"n":"台湾","v":"/area/台湾"},
{"n":"美国","v":"/area/美国"},
{"n":"韩国","v":"/area/韩国"},
{"n":"日本","v":"/area/日本"},
{"n":"泰国","v":"/area/泰国"},
{"n":"新加坡","v":"/area/新加坡"},
{"n":"马来西亚","v":"/area/马来西亚"},
{"n":"印度","v":"/area/印度"}
]},
{"key":"year","name":"年份","value":[
{"n":"全部","v":""},
{"n":"2023","v":"/year/2023"},
{"n":"2022","v":"/year/2022"},
{"n":"2021","v":"/year/2021"},
{"n":"2020","v":"/year/2020"},
{"n":"2019","v":"/year/2019"},
{"n":"2018","v":"/year/2018"},
{"n":"2017","v":"/year/2017"},
{"n":"2016","v":"/year/2016"},
{"n":"2015","v":"/year/2015"},
{"n":"2014","v":"/year/2014"},
{"n":"2013","v":"/year/2013"},
{"n":"2012","v":"/year/2012"},
{"n":"2011","v":"/year/2011"},
{"n":"2010","v":"/year/2010"}
]},
{"key":"lang","name":"语言","value":[
{"n":"全部","v":""},
{"n":"国语","v":"/lang/国语"},
{"n":"英语","v":"/lang/英语"},
{"n":"粤语","v":"/lang/粤语"},
{"n":"闽南语","v":"/lang/闽南语"},
{"n":"韩语","v":"/lang/韩语"},
{"n":"日语","v":"/lang/日语"}
]},
{"key":"by","name":"排序","value":[
{"n":"时间","v":"/by/time"},
{"n":"人气","v":"/by/hits"},
{"n":"评分","v":"/by/score"}
]}]
},
    filter_def:{
        1:{cateId:'1'},
        2:{cateId:'2'},
        3:{cateId:'3'},
        4:{cateId:'4'}
    },
    searchUrl:'/index.php/vod/search/page/fypage/wd/**.html',
    // class_parse: '.navbar-items li:gt(1):lt(8);a&&title;a&&href;.*/(.*?).html',
    class_parse: '.navbar-items li;a&&title;a&&href;/(\\d+).html',
    lazy:`js:
        var html = JSON.parse(request(input).match(/r player_.*?=(.*?)</)[1]);
        var url = html.url;
        if (html.encrypt == '1') {
            url = unescape(url)
        } else if (html.encrypt == '2') {
            url = unescape(base64Decode(url))
        }
        if (/m3u8|mp4/.test(url)) {
            input = url
        } else {
            input
        }
    `,
}
